# Setup
title:               Jeremy Low
tagline:             'Ruminations...'
description:         'A home for essays. Written by <a href="https://twitter.com/jrmy_low" >@jrmy_low</a>. <br><br>To get in touch, please check out the contact page below.'
disclaimer:          "Opinions my own, not my employer's."
url:                 https://jrmylow.com
baseurl:             ''
paginate:            5
permalink:           pretty

# Include directories
include: ['_pages']

# About/contact
author:
  name:             Jeremy Low
  gh_url:           jrmylow
  tw_url:           jrmy_low
  md_url:           '@jrmylow@mastodon.world'
  email:            hello@jrmylow.com
  hn_url:           jrmylow

# Gems
plugins:
  - jekyll-paginate

kramdown:
  auto_ids: true
  auto_id_stripping: false
  toc_levels: 1..6

# Custom vars
theme_name:          Lanyon
theme_url:           https://lanyon.getpoole.com/
theme_version:       1.1.0
google_analytics_id: #UA-XXXX-Y
