# Setup
title:               Jeremy Low
tagline:             'Ruminations...'
description:         'A home for essays. Written by <a href="https://twitter.com/jrmy_low" target="_blank">@jrmy_low</a>. <br><br>To get in touch, please check out the contact page below.'
disclaimer:          "Opinions my own, not my employer's."
url:                 https://jrmylow.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:             Jeremy Low
  tw_url:           https://twitter.com/jrmylow
  md_url:           '@jrmylow@mastodon.world'
  email:            hello@jrmylow.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
theme_name:          Lanyon
theme_url:           https://lanyon.getpoole.com/
theme_version:       1.1.0
google_analytics_id: #UA-XXXX-Y
